# Generated by Django 4.2 on 2024-01-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_cd', models.CharField(db_comment='作業コード', max_length=30, verbose_name='作業コード')),
                ('category', models.CharField(blank=True, db_comment='カテゴリ', max_length=30, null=True, verbose_name='カテゴリ')),
                ('name', models.CharField(blank=True, db_comment='作業名', max_length=30, null=True, verbose_name='作業名')),
                ('description', models.CharField(blank=True, db_comment='説明', max_length=100, null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新日時', null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '作業項目',
                'verbose_name_plural': '作業項目一覧',
                'db_table': 'task_items',
                'db_table_comment': '作業項目',
            },
        ),
        migrations.AddConstraint(
            model_name='taskitem',
            constraint=models.UniqueConstraint(fields=('task_cd',), name='task_cd'),
        ),
    ]
