# Generated by Django 4.2 on 2024-05-08 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_comment='テンプレート名', max_length=30, null=True, verbose_name='テンプレート名')),
                ('desc', models.CharField(blank=True, db_comment='説明', max_length=50, null=True, verbose_name='説明')),
                ('detail', models.CharField(blank=True, db_comment='詳細', max_length=50, null=True, verbose_name='詳細')),
                ('task_hours', models.DecimalField(blank=True, db_comment='所要時間', decimal_places=1, max_digits=3, null=True, verbose_name='所要時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('task_item', models.ForeignKey(blank=True, db_comment='作業内容', null=True, on_delete=django.db.models.deletion.PROTECT, to='master.taskitem', to_field='task_cd', verbose_name='作業內容')),
            ],
            options={
                'verbose_name': '作業内容テンプレート',
                'verbose_name_plural': '作業内容テンプレート一覧',
                'db_table': 'task_templates',
                'db_table_comment': '作業内容テンプレート',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_comment='テンプレート名', max_length=30, null=True, verbose_name='テンプレート名')),
                ('desc', models.CharField(blank=True, db_comment='説明', max_length=50, null=True, verbose_name='説明')),
                ('start_time', models.TimeField(blank=True, db_comment='開始時間', null=True, verbose_name='開始時間')),
                ('end_time', models.TimeField(blank=True, db_comment='終了時間', null=True, verbose_name='終了時間')),
                ('break_hours', models.DecimalField(blank=True, db_comment='休憩時間', decimal_places=1, max_digits=3, null=True, verbose_name='休憩時間')),
                ('work_hours', models.DecimalField(blank=True, db_comment='作業時間', decimal_places=1, max_digits=3, null=True, verbose_name='作業時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='作成日時', null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新日時', null=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(blank=True, db_comment='ユーザー', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '作業報告テンプレート',
                'verbose_name_plural': '作業報告テンプレート一覧',
                'db_table': 'report_templates',
                'db_table_comment': '作業報告テンプレート',
            },
        ),
    ]
